name: Nightly Snapshot Build
on:
  schedule:
    - cron: "21 3 * * *"
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_NAME: 611364707713.dkr.ecr.us-west-2.amazonaws.com/adot-autoinstrumentation-java-nightly

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-candidate-image: ${{ steps.imageNameOutput.outputs.rcImage }}
      time_stamp_tag: ${{ steps.generate_time_stamp.outputs.nowTimeTag}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Log in to AWS ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws

      - name: Build snapshot with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace -PenableCoverage=true -PtestUpstreamSnapshots=true
        env:
          PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.JAVA_INSTRUMENTATION_SNAPSHOT_ECR }}
          aws-region: us-west-2

      - name: Login to private aws ecr
        uses: docker/login-action@v3
        with:
          registry: 611364707713.dkr.ecr.us-west-2.amazonaws.com

      - name: Get current version
        shell: bash
        run: |
          echo "ADOT_JAVA_VERSION=$(./gradlew printVersion -q -PtestUpstreamSnapshots=true )" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set current date as env variable
        id: generate_time_stamp
        run: echo "nowTimeTag=$(date +'%Y-%m-%dT%H-%M-%S')" >> $$GITHUB_OUTPUT

      - name: Set image name to output
        id: imageNameOutput
        run: echo "rcImage=${{ env.IMAGE_NAME }}:${{steps.generate_time_stamp.outputs.nowTimeTag}}" >> "$GITHUB_OUTPUT"

      - name: Build image for testing
        uses: docker/build-push-action@v5
        with:
          push: false
          build-args: "ADOT_JAVA_VERSION=${{ env.ADOT_JAVA_VERSION }}"
          context: .
          platforms: linux/amd64
          tags: ${{ steps.imageNameOutput.outputs.rcImage}}
          load: true

      - name: Test docker image
        shell: bash
        run: .github/scripts/test-adot-javaagent-image.sh "${{ steps.imageNameOutput.outputs.rcImage }}" "${{ env.ADOT_JAVA_VERSION }}"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: "ADOT_JAVA_VERSION=${{ env.ADOT_JAVA_VERSION }}"
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.imageNameOutput.outputs.rcImage}}

      - name: Upload to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: aws-opentelemetry-agent.jar
          path: otelagent/build/libs/aws-opentelemetry-agent-*.jar

      - name: Build and push Sample-Apps without Auto-Instrumentation Agent
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jibBuildWithoutAgent
        env:
          COMMIT_HASH: ${{ steps.generate_time_stamp.outputs.nowTimeTag }}

  # Non-AppSignals e2e tests with Operator
  e2e-operator-test:
    needs: build
    uses: ./.github/workflows/e2e-tests-with-operator.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      image_tag: ${{ needs.build.outputs.time_stamp_tag }}
      image_name: ${{ env.IMAGE_NAME }}
      caller-workflow-name: 'nightly-upstream-snapshot-build'

  # Non-AppSignals e2e tests where SampleApp has Java Agent
  e2e-test:
    needs: build
    uses: ./.github/workflows/e2e-tests-with-embedded-java-agent.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      image_tag: ${{ needs.build.outputs.time_stamp_tag }}
      caller-workflow-name: 'nightly-upstream-snapshot-build'

  # AppSignals Contract Tests
  contract-tests:
    needs: build
    uses: ./.github/workflows/contract-tests.yml
    secrets: inherit
    with:
      aws-region: {{ env.AWS_DEFAULT_REGION }}
      caller-workflow-name: 'nightly-upstream-snapshot-build'

  # AppSignals specific e2e tests
  appsignals-e2e-test:
    concurrency:
      group: e2e-adot-test
      cancel-in-progress: false
    needs: build
    uses: ./.github/workflows/appsignals-e2e-eks-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: "e2e-adot-test"
      appsignals-adot-image-name: ${{ needs.build.outputs.release-candidate-image }}
      caller-workflow-name: 'nightly-upstream-snapshot-build'

  publish-build-status:
    needs: [ build ]
    if: ${{ always() }}
    uses: ./.github/workflows/publish-status.yml
    with:
      namespace: 'ADOT/GitHubActions'
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      workflow: nightly-upstream-snapshot-build
      success: ${{  needs.build.result == 'success' }}
      region: us-west-2
    secrets:
      roleArn: ${{ secrets.METRICS_ROLE_ARN }}
