name: Testing

on:
  push:
    branches:
      - main-build-test

concurrency:
  group: 'pulse-pg-2'
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  e2e-test:
    uses: ./.github/workflows/appsignals-e2e-eks-test.yml
    secrets: inherit
    with:
      aws-region: 'us-east-1'
      test-cluster-name: 'pulse-pg-2'
      appsignals-adot-image-name: 'public.ecr.aws/aws-observability/adot-autoinstrumentation-java:v1.31.2'
      caller-workflow-name: 'test'